import type { Metadata } from "next";
import Navigation from '../components/Navigation';
import { Inter } from "next/font/google";
//import "./app.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"
        href="https://bootswatch.com/5/flatly/bootstrap.min.css" 
      />
      </head>
      <body>

        <Navigation />
        <div className="container p-4">{children}</div>
        
        </body>
    </html>
  );
}
